<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form id="dataForm">
        <input type="text" id="name" placeholder="nom">
        <br>
        <input type="text" id="firstname" placeholder="prénom">
        <br>
        <input type="number" id="age" placeholder="âge">
        <br>
        <button type="submit">enregistrer</button>
    </form>
    <p id="datas"></p>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="script.js"></script>
</body>

</html>